[package]
org = "dsa612s"
name = "rental_server"
version = "1.0.0"
distribution = "2201.13.5"
authors = ["DSA612S Group"]
keywords = ["grpc", "protobuf", "rental", "accommodation"]
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = false
offline = false
